In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
#sentences
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'i am a goof boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a goof boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## DEfine the vocabulary Size
vocab_size = 10000


In [6]:
### one hot representation for  every word
one_hot_repr=[one_hot(words,vocab_size)for words in sent]
one_hot_repr


[[8322, 8564, 8074, 3723],
 [8322, 8564, 8074, 3899],
 [8322, 3025, 8074, 7090],
 [812, 2397, 774, 6313, 6263],
 [812, 2397, 774, 8545, 9477],
 [365, 8322, 3504, 8074, 6769],
 [1439, 9894, 4946, 8545]]

In [7]:
#Word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np 
import pandas as pd


In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8322 8564 8074 3723]
 [   0    0    0    0 8322 8564 8074 3899]
 [   0    0    0    0 8322 3025 8074 7090]
 [   0    0    0  812 2397  774 6313 6263]
 [   0    0    0  812 2397  774 8545 9477]
 [   0    0    0  365 8322 3504 8074 6769]
 [   0    0    0    0 1439 9894 4946 8545]]


In [10]:
#feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 284ms/step


array([[[-2.51678582e-02, -4.42673080e-02,  1.66259669e-02,
         -3.27446461e-02,  3.52033265e-02, -4.16703820e-02,
         -3.44828963e-02,  3.14855836e-02, -2.02251803e-02,
          4.39930670e-02],
        [-2.51678582e-02, -4.42673080e-02,  1.66259669e-02,
         -3.27446461e-02,  3.52033265e-02, -4.16703820e-02,
         -3.44828963e-02,  3.14855836e-02, -2.02251803e-02,
          4.39930670e-02],
        [-2.51678582e-02, -4.42673080e-02,  1.66259669e-02,
         -3.27446461e-02,  3.52033265e-02, -4.16703820e-02,
         -3.44828963e-02,  3.14855836e-02, -2.02251803e-02,
          4.39930670e-02],
        [-2.51678582e-02, -4.42673080e-02,  1.66259669e-02,
         -3.27446461e-02,  3.52033265e-02, -4.16703820e-02,
         -3.44828963e-02,  3.14855836e-02, -2.02251803e-02,
          4.39930670e-02],
        [-4.82201576e-05, -2.07892191e-02,  4.40361015e-02,
          3.33934911e-02, -3.52388024e-02, -1.72705054e-02,
          3.20041180e-03, -2.82556415e-02, -1.206693

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 8322, 8564, 8074, 3723])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 110ms/step


array([[-2.5167858e-02, -4.4267308e-02,  1.6625967e-02, -3.2744646e-02,
         3.5203326e-02, -4.1670382e-02, -3.4482896e-02,  3.1485584e-02,
        -2.0225180e-02,  4.3993067e-02],
       [-2.5167858e-02, -4.4267308e-02,  1.6625967e-02, -3.2744646e-02,
         3.5203326e-02, -4.1670382e-02, -3.4482896e-02,  3.1485584e-02,
        -2.0225180e-02,  4.3993067e-02],
       [-2.5167858e-02, -4.4267308e-02,  1.6625967e-02, -3.2744646e-02,
         3.5203326e-02, -4.1670382e-02, -3.4482896e-02,  3.1485584e-02,
        -2.0225180e-02,  4.3993067e-02],
       [-2.5167858e-02, -4.4267308e-02,  1.6625967e-02, -3.2744646e-02,
         3.5203326e-02, -4.1670382e-02, -3.4482896e-02,  3.1485584e-02,
        -2.0225180e-02,  4.3993067e-02],
       [-4.8220158e-05, -2.0789219e-02,  4.4036102e-02,  3.3393491e-02,
        -3.5238802e-02, -1.7270505e-02,  3.2004118e-03, -2.8255641e-02,
        -1.2066938e-02,  2.3134161e-02],
       [ 4.2366114e-02, -4.6576705e-02, -6.9167465e-04,  2.7625773e-02,
   